select * from VW_FNC_CONTR_CURRIC_LANCAMENTO_DESC_ALUNO 
where aluno_nome = 'LARA PINTO MOREIRA'

select * 
-- UPDATE LAN SET LAN.TIPO_ID = 1 , LAN.ATUALIZADO_EM = , LAN.ATULAIZADO_POR = 11717 
from financeiro_lancamento lan
where id = 8900


begin tran 
DECLARE @DATAEXECUCAO DATETIME      
SET @DATAEXECUCAO = CAST( CONVERT(VARCHAR(19),GETDATE(),120) AS DATETIME) 

UPDATE LAN SET LAN.TIPO_ID = 1 , LAN.ATUALIZADO_EM = @DATAEXECUCAO , LAN.atualizado_por = 11717 
from financeiro_lancamento lan
where id = 8900

EXEC SP_GERAR_LOG_EM_LOTE_UPDATE 'FINANCEIRO_LANCAMENTO', @DATAEXECUCAO, 11717,null, null,null   

-- COMMIT
-- ROLLBACK 
