-- DROP TABLE TMP_IMP_CARGA_ALUNO_DB_SA

SELECT DISTINCT USUARIOPERFIL AS PERFIL_NOME, USUARIOID AS ALUNO_ID, USUARIONOME AS ALUNO_NOME, 
       CASE WHEN USUARIOSERIE LIKE '%EXTENSIVO%' THEN '3ª SÉRIE' ELSE USUARIOSERIE END AS GRADE_NOME, 
	   USUARIOSTURMA AS TURMA_ID, ESCOLAID AS ESCOLA_ID, 
	   ESCOLANOME AS ESCOLA_NOME, TURMANOME AS TURMA_NOME 
	   INTO TMP_IMP_CARGA_ALUNO_DB_SA 
 from (
select * from tmp_imp_aluno_dombosco union 
select * from tmp_imp_aluno_santoanjo) as tab



