-- use educat_cmmg

select count(1) from CMMG_APPLICATION_ANSWER
select count(1) from CMMG_APPLICATION_APPLICATION
select count(1) from CMMG_DADOS_EXPORTACAO
select count(1) from CMMG_EXAM_EXAM
select count(1) from CMMG_EXAM_EXAMITEM
select count(1) from CMMG_ITEM_ALTERNATIVE
select count(1) from CMMG_ITEM_ITEM
select count(1) from CMMG_USUARIO







DROP TABLE CMMG_APPLICATION_ANSWER
DROP TABLE CMMG_APPLICATION_APPLICATION
DROP TABLE CMMG_DADOS_EXPORTACAO
DROP TABLE CMMG_EXAM_EXAM
DROP TABLE CMMG_EXAM_EXAMITEM
DROP TABLE CMMG_ITEM_ALTERNATIVE
DROP TABLE CMMG_ITEM_ITEM
DROP TABLE CMMG_USUARIO


  SELECT * INTO CMMG_APPLICATION_ANSWER      FROM EXAMS_CMMG..APPLICATION_ANSWER     
  SELECT * INTO CMMG_APPLICATION_APPLICATION FROM EXAMS_CMMG..APPLICATION_APPLICATION
  SELECT * INTO CMMG_DADOS_EXPORTACAO        FROM EXAMS_CMMG..VW_DADOS_EXPORTACAO       
  SELECT * INTO CMMG_EXAM_EXAM               FROM EXAMS_CMMG..EXAM_EXAM              
  SELECT * INTO CMMG_EXAM_EXAMITEM           FROM EXAMS_CMMG..EXAM_EXAMITEM          
  SELECT * INTO CMMG_ITEM_ALTERNATIVE        FROM EXAMS_CMMG..ITEM_ALTERNATIVE       
  SELECT * INTO CMMG_ITEM_ITEM               FROM EXAMS_CMMG..ITEM_ITEM              
  SELECT id,email, name INTO CMMG_USUARIO    FROM EXAMS_CMMG..AUTH_USER   
  


  