--****** PRIMEIRO CASO - DATA INICIO OU DATA FIM DO GRUPO NAO BATE

ALTER view VW_AULA_GRUPO_DIVERGENCIA_DATA_INICIO_OU_TERMINO AS 

  SELECT ID, DATA_INICIO, INICIO, DATA_TERMINO, TERMINO, 
         DIFERENCA_INICIO  = CASE WHEN data_inicio <> INICIO   THEN 'DIFERENTE' ELSE '' END , 
         DIFERENCA_TERMINO = CASE WHEN data_termino <> TERMINO THEN 'DIFERENTE' ELSE '' END 
   FROM VW_ACAD_AULA_GRUPO_DIVERGENCIA
  WHERE  (data_inicio <> INICIO OR 
         data_termino <> TERMINO) AND 
		 TIPO = 'DIVERGENCIA_DATAS'

