
WITH CTE_BOLETO_PAGO AS (
			SELECT BOL.lancamento_id
			  FROM FINANCEIRO_LANCAMENTOBOLETO BOL JOIN BOLETOS_SERVICE.db_owner.vw_boleto BLT ON (BLT.boleto_id = BOL.boleto_id)
			 WHERE BLT.boleto_status = 'PAID'
)
	,	CTE_LANCAMENTO_PROBLEMA AS (
			SELECT FNC.LANCAMENTO_ID, FNC.LANCAMENTO_STATUS_NOME, FNC.LANCAMENTO_VALOR_PAGO, BOL.BOLETO_STATUS, BOL.boleto_id 
			  FROM VW_FNC_CONTR_CURRIC_LANCAMENTO_DESC_ALUNO FNC JOIN BOLETOS_SERVICE.db_owner.vw_boleto BOL ON (FNC.LANC_BOLETO_BOLETO_ID = BOL.boleto_id)
			                                                LEFT JOIN CTE_BOLETO_PAGO BLP ON (BLP.lancamento_id = FNC.LANCAMENTO_ID)
			WHERE BLP.lancamento_id IS NULL AND 
			      BOL.boleto_status = 'pending' AND 
				  FNC.LANCAMENTO_STATUS_NOME = 'PAGO'
) 

           SELECT DISTINCT CON.ALUNO_RA, CON.ALUNO_NOME,  PRO.LANCAMENTO_ID, PRO.LANCAMENTO_STATUS_NOME, PRO.LANCAMENTO_VALOR_PAGO, PRO.BOLETO_STATUS 
		     FROM CTE_LANCAMENTO_PROBLEMA PRO JOIN vw_contrato_parcela_desconto_aluno CON ON (PRO.LANCAMENTO_ID = CON.lancamento_id)

           ORDER BY 1