WITH	CTE_TELEFONE1 AS (
			SELECT ALUNO_CPF, ALUNO_TELEFONE_FIXO AS TELEFONE, TIPO = 2 FROM VW_PES_PESSOA
			WHERE ORIGEM = 'MATRICULA' AND 
				  aluno_telefone_fixo IS NOT NULL 
)
	,	CTE_TELEFONE2 AS (
			SELECT ALUNO_CPF, ALUNO_TELEFONE AS TELEFONE, TIPO = 2 FROM VW_PES_PESSOA
			WHERE ORIGEM = 'MATRICULA' AND 
				  aluno_telefone IS NOT NULL 
)
	,	CTE_TELEFONE3 AS (
			SELECT ALUNO_CPF, ALUNO_TELEFONE_EXTRA AS TELEFONE, TIPO = 2 FROM VW_PES_PESSOA
			WHERE ORIGEM = 'MATRICULA' AND 
				  ALUNO_TELEFONE_EXTRA IS NOT NULL 
)
	,	CTE_TELEFONES AS (
			SELECT * FROM CTE_TELEFONE1 UNION 
			SELECT * FROM CTE_TELEFONE2 UNION 
			SELECT * FROM CTE_TELEFONE3 
)


		--	INSERT INTO pessoas_telefone
			SELECT DISTINCT TEL.TELEFONE, PRINCIPAL = 0, PES.ID, TEL.TIPO FROM CTE_TELEFONES TEL LEFT JOIN PESSOAS_PESSOA PES ON (TEL.ALUNO_CPF = PES.CPF)
			WHERE PES.ID IS NOT NULL  AND 
			      NOT EXISTS (SELECT 1
				                FROM pessoas_telefone PTS 
							   WHERE PTS.PESSOA_ID = PES.ID AND 
							         TEL.TELEFONE = REPLACE(REPLACE(REPLACE(REPLACE(PTS.NUMERO, ')', ''), '(', ''), '_', ''), '-', ''))



									