SELECT * INTO BKP_CURRICULOS_ALUNO_ENADE_15012020 FROM CURRICULOS_ALUNO_ENADE

BEGIN TRAN

DECLARE @ALUNO             VARCHAR(100)
DECLARE @CPF               VARCHAR(20)
DECLARE @MENSAGEM          VARCHAR(500)
DECLARE @ANOENADE          INT
DECLARE @CURRICULOALUNO_ID INT

BEGIN
  DECLARE C_ENADE CURSOR FOR
  
  SELECT ALUNO, MENSAGEM, CPF, ANOENADE FROM DADOSENADE2019_V2
  WHERE ALTERADO = 0

  OPEN C_ENADE
  FETCH NEXT FROM C_ENADE INTO @ALUNO, @MENSAGEM, @CPF, @ANOENADE

  WHILE @@FETCH_STATUS = 0 
  BEGIN
  
  IF (SELECT COUNT(1)
      FROM CURRICULOS_ALUNO_ENADE ALUENADE
      JOIN ACADEMICO_ENADE ENADE ON ENADE.ID = ALUENADE.ENADE_ID
      JOIN CURRICULOS_ALUNO CURRALU ON CURRALU.ID = ALUENADE.CURRICULO_ALUNO_ID
      JOIN ACADEMICO_ALUNO ALUNO ON ALUNO.ID = CURRALU.ALUNO_ID
      JOIN PESSOAS_PESSOA PESSOA ON PESSOA.ID = ALUNO.PESSOA_ID
      WHERE PESSOA.CPF = @CPF
        AND ENADE.ANO = @ANOENADE) > 0
  BEGIN
    UPDATE ALUENADE SET MENSAGEM = @MENSAGEM
    FROM CURRICULOS_ALUNO_ENADE ALUENADE
    JOIN ACADEMICO_ENADE ENADE ON ENADE.ID = ALUENADE.ENADE_ID
    JOIN CURRICULOS_ALUNO CURRALU ON CURRALU.ID = ALUENADE.CURRICULO_ALUNO_ID
    JOIN ACADEMICO_ALUNO ALUNO ON ALUNO.ID = CURRALU.ALUNO_ID
    JOIN PESSOAS_PESSOA PESSOA ON PESSOA.ID = ALUNO.PESSOA_ID
    WHERE PESSOA.CPF = @CPF
      AND ENADE.ANO = @ANOENADE
  END
  ELSE
  BEGIN
    IF (SELECT COUNT(1)
        FROM CURRICULOS_ALUNO CURRALU
		JOIN ACADEMICO_ALUNO ALUNO ON ALUNO.ID = CURRALU.ALUNO_ID
        JOIN PESSOAS_PESSOA PESSOA ON PESSOA.ID = ALUNO.PESSOA_ID
        WHERE PESSOA.CPF = @CPF) > 0
	BEGIN
	  SELECT @CURRICULOALUNO_ID = CURRALU.ID
        FROM CURRICULOS_ALUNO CURRALU
		JOIN ACADEMICO_ALUNO ALUNO ON ALUNO.ID = CURRALU.ALUNO_ID
        JOIN PESSOAS_PESSOA PESSOA ON PESSOA.ID = ALUNO.PESSOA_ID
        WHERE PESSOA.CPF = @CPF
		  --AND CURRALU.STATUS_ID = 13

	  INSERT INTO CURRICULOS_ALUNO_ENADE (CRIADO_EM, ATUALIZADO_EM, MENSAGEM, ENADE_ID, CURRICULO_ALUNO_ID)
	  VALUES (GETDATE(), GETDATE(), @MENSAGEM, 36, @CURRICULOALUNO_ID)
	END
  END

  IF @@ROWCOUNT > 0
    UPDATE DADOSENADE2019_V2 SET ALTERADO = 1
    WHERE CPF      = @CPF
      AND ANOENADE = @ANOENADE
	
  FETCH NEXT FROM C_ENADE INTO @ALUNO, @MENSAGEM, @CPF, @ANOENADE
  END
  CLOSE C_ENADE
  DEALLOCATE C_ENADE

END

ROLLBACK
COMMIT