CREATE OR ALTER VIEW VW_COMPARACAO_CORRECAO_GABARITO AS 
SELECT AUT.LAST_NAME, COR.REDACAO_ID, COR.ID_CORRETOR, 
	   TIPO_REDACAO = CASE WHEN COR.ID_TIPO_CORRECAO = 5 THEN 'OURO' 
	               WHEN COR.ID_TIPO_CORRECAO = 6 THEN 'MODA' ELSE 'ERRO' END,
       SITC.DESCRICAO AS SITUCAO_CORRECAO, 
       COR.COMPETENCIA1,
       COR.COMPETENCIA2,
       COR.COMPETENCIA3,
       COR.COMPETENCIA4,
       COR.COMPETENCIA5,
	   CASE WHEN COR.COMPETENCIA5 = -1 THEN 'SIM' ELSE '' END AS DDH_CORRECAO,
	   COR.NOTA_FINAL AS NOTA_FINAL_CORRECAO,
       SITG.DESCRICAO AS SITUACAO_GABARITO, 
       GAB.ID_COMPETENCIA1 AS COMPETENCIA1_GABARITO,
       GAB.ID_COMPETENCIA2 AS COMPETENCIA2_GABARITO,
       GAB.ID_COMPETENCIA3 AS COMPETENCIA3_GABARITO,
       GAB.ID_COMPETENCIA4 AS COMPETENCIA4_GABARITO,
       GAB.ID_COMPETENCIA5 AS COMPETENCIA5_GABARITO,	   
	   CASE WHEN GAB.ID_COMPETENCIA5 = -1 THEN 'SIM' ELSE '' END AS DDH_GABARITO,
	   GAB.NOTA_FINAL AS NOTA_FINAL_GABARITO, 

	   ABS(COR.COMPETENCIA1- GAB.ID_COMPETENCIA1) AS DIF1		   ,
       ABS(COR.COMPETENCIA2- GAB.ID_COMPETENCIA2) AS DIF2		   ,
       ABS(COR.COMPETENCIA3- GAB.ID_COMPETENCIA3) AS DIF3		   ,
       ABS(COR.COMPETENCIA4- GAB.ID_COMPETENCIA4) AS DIF4		   ,
       ABS(COR.COMPETENCIA5- GAB.ID_COMPETENCIA5) AS DIF5		   ,
	   ABS(COR.NOTA_FINAL  - GAB.NOTA_FINAL     ) AS DIF_NOTAFINAL ,

	   COR.DATA_INICIO, COR.DATA_TERMINO, 
	   DATEDIFF(MINUTE,COR.DATA_INICIO,COR.DATA_TERMINO) AS TEMPO_GASTO_EM_MINUTOS

  FROM CORRECOES_CORRECAO COR WITH(NOLOCK) JOIN CORRECOES_GABARITO GAB WITH(NOLOCK) ON (COR.REDACAO_ID = GAB.REDACAO_ID)
                                           JOIN AUTH_USER          AUT WITH(NOLOCK) ON (AUT.ID         = COR.ID_CORRETOR)
										   JOIN CORRECOES_SITUACAO SITC WITH(NOLOCK) ON (SITC.ID       = COR.ID_CORRECAO_SITUACAO)
										   JOIN CORRECOES_SITUACAO SITG WITH(NOLOCK) ON (SITG.ID       = GAB.ID_CORRECAO_SITUACAO)
/*
SELECT * 
FROM VW_COMPARACAO_CORRECAO_GABARITO
WHERE --COR.REDACAO_ID = 13734 AND 
      ID_CORRETOR = 14572
*/