create or alter view vw_redacao_auditoria_nota_1000 as
SELECT distinct RED.ID AS REDACAO_ID, RED.ID_PROJETO
FROM correcoes_redacao RED JOIN CORRECOES_CORRECAO COR1 ON (RED.ID = COR1.REDACAO_ID AND RED.ID_PROJETO = COR1.ID_PROJETO AND COR1.ID_TIPO_CORRECAO = 1)
                           JOIN CORRECOES_CORRECAO COR2 ON (RED.ID = COR2.REDACAO_ID AND RED.ID_PROJETO = COR2.ID_PROJETO AND COR2.ID_TIPO_CORRECAO = 2)
                      left JOIN CORRECOES_CORRECAO COR3 ON (RED.ID = COR3.REDACAO_ID AND RED.ID_PROJETO = COR3.ID_PROJETO AND COR3.ID_TIPO_CORRECAO = 3)
                      left JOIN CORRECOES_CORRECAO COR4 ON (RED.ID = COR4.REDACAO_ID AND RED.ID_PROJETO = COR4.ID_PROJETO AND COR4.ID_TIPO_CORRECAO = 4)
WHERE (COR1.nota_final = 1000 and COR2.nota_final = 1000) OR 
      (COR1.nota_final = 1000 AND COR3.nota_final = 1000) OR 
	  (COR2.NOTA_FINAL = 1000 AND COR3.nota_final = 1000) OR 
	  (COR4.nota_final = 1000)
      
