

declare @data date = dateadd(day,-1,cast('2019-12-10 10:32:00' as date));

WITH CTE_REDACAO AS (
			SELECT red.id, red.co_barra_redacao, red.co_inscricao, red.link_imagem_recortada, red.link_imagem_original,
			       red.nota_final, red.co_formulario, red.id_prova, red.id_correcao_situacao, red.id_redacao_situacao,
			       red.id_projeto, red.nota_competencia1, red.nota_competencia2, red.nota_competencia3, red.nota_competencia4, 
				   red.nota_competencia5, red.data_inicio, red.data_termino,
				     CONCEITO_MAX_COMPETENCIA1 =  pro.peso_competencia * 5
                   , CONCEITO_MAX_COMPETENCIA2 =  pro.peso_competencia * 5
                   , CONCEITO_MAX_COMPETENCIA3 =  pro.peso_competencia * 5
                   , CONCEITO_MAX_COMPETENCIA4 =  pro.peso_competencia * 5
                   , CONCEITO_MAX_COMPETENCIA5 =  pro.peso_competencia * 5,
				   N02.SG_UF_PROVA
			-- select  count(red.id)
			--INTO #temp_maior
			  FROM EXT_CORRECOES_REDACAO RED join EXT_projeto_projeto pro on (red.id_projeto = pro.id)
			                                 JOIN EXT_INEP_N02 N02 ON (N02.CO_INSCRICAO = RED.co_inscricao)
                     
			 WHERE cast(red.data_termino as date) = @data  AND
			       red. cancelado = 0 AND RED.id_STATUS = 4 AND 
				   red.id_redacaoouro IS NULL 
				   --AND   datepart (hour, red.data_termino) <= 11
				 --  GROUP BY datepart (hour, red.data_termino)
) 

	,	CTE_USUARIO AS (
			SELECT ID, USERNAME
			  FROM EXT_AUTH_USER  
) 

	,	CTE_SITUACAO AS (
			SELECT ID, SIGLA 
			  FROM EXT_CORRECOES_SITUACAO  
)

	,	CTE_CORRECAO AS (
			SELECT cor.id, cor.data_inicio, cor.data_termino, cor.nota_final,
                   cor.nota_competencia1, cor.nota_competencia2, cor.nota_competencia3, cor.nota_competencia4, cor.nota_competencia5, 
                   tempo_em_correcao = case when COR.TEMPO_EM_CORRECAO > 1200 then 1200 else  COR.TEMPO_EM_CORRECAO end,
				   cor.id_correcao_situacao,
                   cor.id_corretor, cor.id_status, cor.tipo_auditoria_id, cor.id_tipo_correcao, cor.redacao_id, USU.USERNAME AS CPF_CORRETOR, 
				   case when cor.competencia5 = -1 then 1 else 0 end infere_dh, 
				   sit.sigla as sigla_correcao_situacao
			  FROM  EXT_correcoes_correcao cor JOIN CTE_USUARIO USU ON (USU.ID = COR.id_corretor)
			                                   join CTE_SITUACAO sit on (sit.id = cor.id_correcao_situacao)
) 


INSERT INTO INEP_N59_2020 (REDACAO_ID, LOTE_ID, PROJETO_ID, CRIADO_EM, DATA_INICIO, DATA_TERMINO, CO_PROJETO, TP_ORIGEM, CO_INSCRICAO, CO_ETAPA, 
SG_UF_PROVA, NU_CONCEITO_MAX_COMPETENCIA1, NU_CONCEITO_MAX_COMPETENCIA2, NU_CONCEITO_MAX_COMPETENCIA3, NU_CONCEITO_MAX_COMPETENCIA4, 
NU_CONCEITO_MAX_COMPETENCIA5, CO_TIPO_AVALIACAO, LINK_IMAGEM_RECORTADA, NU_CPF_AV1, DT_INICIO_AV1, DT_FIM_AV1, NU_TEMPO_AV1, 
ID_LOTE_AV1, CO_SITUACAO_REDACAO_AV1, SG_SITUACAO_REDACAO_AV1, IN_FERE_DH_AV1, NU_NOTA_AV1, NU_NOTA_COMP1_AV1, NU_NOTA_COMP2_AV1, 
NU_NOTA_COMP3_AV1, NU_NOTA_COMP4_AV1, NU_NOTA_COMP5_AV1, NU_CPF_AV2, DT_INICIO_AV2, DT_FIM_AV2, NU_TEMPO_AV2, ID_LOTE_AV2, 
CO_SITUACAO_REDACAO_AV2, SG_SITUACAO_REDACAO_AV2, IN_FERE_DH_AV2, NU_NOTA_AV2, NU_NOTA_COMP1_AV2, NU_NOTA_COMP2_AV2, 
NU_NOTA_COMP3_AV2, NU_NOTA_COMP4_AV2, NU_NOTA_COMP5_AV2, NU_CPF_AV3, DT_INICIO_AV3, DT_FIM_AV3, NU_TEMPO_AV3, ID_LOTE_AV3, 
CO_SITUACAO_REDACAO_AV3, SG_SITUACAO_REDACAO_AV3, IN_FERE_DH_AV3, NU_NOTA_AV3, NU_NOTA_COMP1_AV3, NU_NOTA_COMP2_AV3, NU_NOTA_COMP3_AV3, 
NU_NOTA_COMP4_AV3, NU_NOTA_COMP5_AV3, NU_CPF_AV4, DT_INICIO_AV4, DT_FIM_AV4, NU_TEMPO_AV4, ID_LOTE_AV4, CO_SITUACAO_REDACAO_AV4, 
SG_SITUACAO_REDACAO_AV4, IN_FERE_DH_AV4, NU_NOTA_AV4, NU_NOTA_COMP1_AV4, NU_NOTA_COMP2_AV4, NU_NOTA_COMP3_AV4, NU_NOTA_COMP4_AV4, 
NU_NOTA_COMP5_AV4, NU_NOTA_MEDIA_COMP1, NU_NOTA_MEDIA_COMP2, NU_NOTA_MEDIA_COMP3, NU_NOTA_MEDIA_COMP4, NU_NOTA_MEDIA_COMP5, 
CO_SITUACAO_REDACAO_FINAL,  NU_NOTA_FINAL, CO_JUSTIFICATIVA, NU_CPF_AUDITOR, IN_DIVULGACAO, IN_FERE_DH, STATUS_ID, SUBSTITUIDO_POR) 
select TOP 1000000
 red.id as redacao_id, 
 lote_id = 1,
 red.ID_PROJETO,
 criado_em = dbo.getlocaldate(),
 data_inicio = null, 
 data_termino = null,
 CO_PROJETO = left(RED.co_inscricao, 5) + '01'
 , TP_ORIGEM = 'V'
 , RED.CO_INSCRICAO
 , CO_ETAPA = NULL
 , SG_UF_PROVA = RED.SG_UF_PROVA
 , NU_CONCEITO_MAX_COMPETENCIA1 =  red.CONCEITO_MAX_COMPETENCIA1
 , NU_CONCEITO_MAX_COMPETENCIA2 =  red.CONCEITO_MAX_COMPETENCIA2
 , NU_CONCEITO_MAX_COMPETENCIA3 =  red.CONCEITO_MAX_COMPETENCIA3
 , NU_CONCEITO_MAX_COMPETENCIA4 =  red.CONCEITO_MAX_COMPETENCIA4
 , NU_CONCEITO_MAX_COMPETENCIA5 =  red.CONCEITO_MAX_COMPETENCIA5
 , CO_TIPO_AVALIACAO       = 1
 , LINK_IMAGEM_RECORTADA   = RED.LINK_IMAGEM_RECORTADA
 , NU_CPF_AV1              = COR1.CPF_CORRETOR 
 , DT_INICIO_AV1		   = COR1.DATA_INICIO 
 , DT_FIM_AV1			   = COR1.DATA_TERMINO 
 , NU_TEMPO_AV1			   = COR1.TEMPO_EM_CORRECAO 
 , ID_LOTE_AV1			   = 1 
 , CO_SITUACAO_REDACAO_AV1 = COR1.ID_CORRECAO_SITUACAO 
 , sg_situacao_redacao_av1 = COR1.SIGLA_CORRECAO_SITUACAO
 , IN_FERE_DH_AV1		   = COR1.INFERE_DH 
 , NU_NOTA_AV1			   = COR1.NOTA_FINAL 
 , NU_NOTA_COMP1_AV1	   = COR1.NOTA_COMPETENCIA1 
 , NU_NOTA_COMP2_AV1	   = COR1.NOTA_COMPETENCIA2 
 , NU_NOTA_COMP3_AV1	   = COR1.NOTA_COMPETENCIA3 
 , NU_NOTA_COMP4_AV1	   = COR1.NOTA_COMPETENCIA4 
 , NU_NOTA_COMP5_AV1	   = COR1.NOTA_COMPETENCIA5 
 , NU_CPF_AV2			   = COR2.CPF_CORRETOR  
 , DT_INICIO_AV2		   = COR2.DATA_INICIO  
 , DT_FIM_AV2			   = COR2.DATA_TERMINO  
 , NU_TEMPO_AV2			   = COR2.TEMPO_EM_CORRECAO 
 , ID_LOTE_AV2			   = 1  
 , CO_SITUACAO_REDACAO_AV2 = COR2.ID_CORRECAO_SITUACAO 
 , SG_SITUACAO_REDACAO_AV2 = COR2.SIGLA_CORRECAO_SITUACAO
 , IN_FERE_DH_AV2		   = COR2.INFERE_DH 
 , NU_NOTA_AV2			   = COR2.NOTA_FINAL  
 , NU_NOTA_COMP1_AV2	   = COR2.NOTA_COMPETENCIA1  
 , NU_NOTA_COMP2_AV2	   = COR2.NOTA_COMPETENCIA2  
 , NU_NOTA_COMP3_AV2	   = COR2.NOTA_COMPETENCIA3  
 , NU_NOTA_COMP4_AV2	   = COR2.NOTA_COMPETENCIA4  
 , NU_NOTA_COMP5_AV2	   = COR2.NOTA_COMPETENCIA5  
 , NU_CPF_AV3              = COR3.CPF_CORRETOR  
 , DT_INICIO_AV3		   = COR3.DATA_INICIO  
 , DT_FIM_AV3			   = COR3.DATA_TERMINO  
 , NU_TEMPO_AV3			   = COR3.TEMPO_EM_CORRECAO 
 , ID_LOTE_AV3			   = 1  
 , CO_SITUACAO_REDACAO_AV3 = COR3.ID_CORRECAO_SITUACAO 
 , SG_SITUACAO_REDACAO_AV3 = COR3.SIGLA_CORRECAO_SITUACAO
 , IN_FERE_DH_AV3		   = COR3.INFERE_DH  
 , NU_NOTA_AV3			   = COR3.NOTA_FINAL  
 , NU_NOTA_COMP1_AV3	   = COR3.NOTA_COMPETENCIA1  
 , NU_NOTA_COMP2_AV3	   = COR3.NOTA_COMPETENCIA2  
 , NU_NOTA_COMP3_AV3	   = COR3.NOTA_COMPETENCIA3  
 , NU_NOTA_COMP4_AV3	   = COR3.NOTA_COMPETENCIA4  
 , NU_NOTA_COMP5_AV3	   = COR3.NOTA_COMPETENCIA5  
 , NU_CPF_AV4              = COR4.CPF_CORRETOR     
 , DT_INICIO_AV4		   = COR4.DATA_INICIO   
 , DT_FIM_AV4			   = COR4.DATA_TERMINO   
 , NU_TEMPO_AV4			   = COR4.TEMPO_EM_CORRECAO  
 , ID_LOTE_AV4			   = 1   
 , CO_SITUACAO_REDACAO_AV4 = COR4.ID_CORRECAO_SITUACAO 
 , SG_SITUACAO_REDACAO_AV4 = COR4.SIGLA_CORRECAO_SITUACAO
 , IN_FERE_DH_AV4		   = COR4.INFERE_DH   
 , NU_NOTA_AV4			   = COR4.NOTA_FINAL   
 , NU_NOTA_COMP1_AV4	   = COR4.NOTA_COMPETENCIA1   
 , NU_NOTA_COMP2_AV4	   = COR4.NOTA_COMPETENCIA2   
 , NU_NOTA_COMP3_AV4	   = COR4.NOTA_COMPETENCIA3   
 , NU_NOTA_COMP4_AV4	   = COR4.NOTA_COMPETENCIA4   
 , NU_NOTA_COMP5_AV4	   = COR4.NOTA_COMPETENCIA5   
 , NU_NOTA_MEDIA_COMP1	     = RED.NOTA_COMPETENCIA1 
 , NU_NOTA_MEDIA_COMP2	  	 = RED.NOTA_COMPETENCIA2 
 , NU_NOTA_MEDIA_COMP3	  	 = RED.NOTA_COMPETENCIA3 
 , NU_NOTA_MEDIA_COMP4	  	 = RED.NOTA_COMPETENCIA4 
 , NU_NOTA_MEDIA_COMP5	  	 = RED.NOTA_COMPETENCIA5 
 , CO_SITUACAO_REDACAO_FINAL = RED.ID_REDACAO_SITUACAO 
 --, IN_FERE_DH_FINAL			 = COR7.INFERE_DH
 , NU_NOTA_FINAL			 = RED.NOTA_FINAL  
 , CO_JUSTIFICATIVA			 = NULL 
 , NU_CPF_AUDITOR			 = COR7.CPF_CORRETOR 
 , IN_DIVULGACAO			 = 0 
 , IN_FERE_DH = COR7.INFERE_DH
 , status_id = null 
 , substituido_por = null
from CTE_REDACAO red left  JOIN CTE_CORRECAO COR1 ON (COR1.redacao_id = RED.ID AND COR1.ID_TIPO_CORRECAO = 1) 
                     LEFT  JOIN CTE_CORRECAO COR2 ON (COR2.redacao_id = RED.ID AND COR2.ID_TIPO_CORRECAO = 2) 
                     LEFT JOIN CTE_CORRECAO COR3 ON (COR3.redacao_id = RED.ID AND COR3.ID_TIPO_CORRECAO = 3) 
                     LEFT JOIN CTE_CORRECAO COR4 ON (COR4.redacao_id = RED.ID AND COR4.ID_TIPO_CORRECAO = 4) 
                     LEFT JOIN CTE_CORRECAO COR7 ON (COR7.redacao_id = RED.ID AND COR7.ID_TIPO_CORRECAO = 7) 
					 LEFT JOIN INEP_N59_2020 XXX ON (XXX.REDACAO_ID = RED.ID)
WHERE XXX.ID IS NULL

--select cast (data_termino as date) , count(id)
--from EXT_CORRECOES_REDACAO
--group by cast (data_termino as date) 
--order by 2 desc 

--select * from EXT_CORRECOES_CORRECAO where redacao_id = 880419
--select * from inep_n59_2020
--delete from inep_n59_2020