DECLARE @PROVA VARCHAR(200) = '1ª série - Diagnóstica 2/2020 - 1º dia'
DECLARE @ESCOLA VARCHAR(200) =  'ESC.COOPERATIVA EDUC.DA CIDAD DE S.ROQUE'
DECLARE @GRADE VARCHAR(100) = '1ª série'

SELECT CONVERT(VARCHAR(10),COUNT(DISTINCT ALUNO_NOME)) + ' ALUNOS' 
FROM VW_AGENDAMENTO_PROVA_ALUNO
where ESCOLA_NOME = @ESCOLA and 
      PROVA_NOME = @PROVA  AND 
	  GRADE_NOME = @GRADE

SELECT DISTINCT PROVA_NOME, ESCOLA_NOME, ALUNO_NOME, EXA_TWD_INICIO, EXA_TWD_TERMINO, APP_TWD_INICIO, APP_TWD_TERMINO 
FROM VW_AGENDAMENTO_PROVA_ALUNO
where ESCOLA_NOME = @ESCOLA and 
      PROVA_NOME LIKE   @PROVA  AND 
	  GRADE_NOME = @GRADE
ORDER BY 1,2,3

SELECT  * 
FROM VW_AGENDAMENTO_PROVA_ALUNO
where ESCOLA_NOME = @ESCOLA and 
      PROVA_NOME = @PROVA  AND 
	  GRADE_NOME = @GRADE
ORDER BY 1,2,5,4,3


select * from tmp_imp_bloquear where nome_escola_ava = @ESCOLA



--select * from  tmp_imp_escola_extra_2dia
