-- ######## VALIDACAO DE ESTAGIOS  ######## (TESTES PARA DECIDIR QUAL ESTATUS APLICAR A REDACAO COM BASE NA CONCLUSAO DAS REDACOES)

-- VALIDAR NAS ENTRADAS DAS FILAS

-- **** VALIDACAO ****
/*
	* - CORRECAO = 1 OU 2 
		- SE TODAS AS COMPETENCIAS ESTAO PREENCHIDAS (OU SITUACAO)
		- SE JA NAO EXISTE CORRECAO DE MESMO NIVEL EXISTENTE
		- SE EXISTIR A CONTRA PARTIDA JA CORRIGIDA:
			- SE ESTIVER CONCLUIDA: -DEVE ESTAR CONCLUIDA NA REDACAO (DATA E STATUS) -SE NAO FOI GERADA OUTRA CORRECAO (3, 4 OU AUDITORIA)
			- SE NAO ESTIVER CONCLUIDA: -NAO PODE ESTAR CONCLUIDA NA REDACAO (DATA E STATUS) -DEVE SER GERADO UM REGISTRO NA FILA3, UMA CORRECAO DO TIPO 3, UM REGISTRO NA AUDITORIA (NUNCA NA 4)
	
	* - CORRECAO = 3
		- SE TODAS AS COMPETENCIAS ESTAO PREENCHIDAS (OU SITUACAO)
		- SE EXISTEM PRIMEIRA E SEGUNDA CORRIGIDAS
		- SE JA NAO EXISTE TERCEIRA GRAVADA
	    - SE FOR SOBERANA: -DEVE SER ATUALIZADA A REDACAO (STATUS E DATA) ***  ENCEJA 
		- SE APROVEITOU COM ALGUMA DAS DUAS: -DEVE ESTAR CONCLUIDA NA REDACAO (DATA E STATUS) -SE NAO FOI GERADA OUTRA CORRECAO (4 OU AUDITORIA)
		- SE NAO APROVEITOU: -DEVE SER GERADO UM REGISTRO NA FILA4 OU NA AUDITORIA
		- SE FOR EQUIDISTANTE - GERAR QUARTA  
		- SE FOR DDH, PD PARTE DESCONECTADA (TEM QUE TER PRIMEIRA, SEGUNDA, (TERCEIRA E QUARTA)) - GEROU AUDITORIA? EM QUALQUER ETAPA  
		- SE  FOR 1000 (DUAS ATE A TERCEIRA OU A QUARTA SER 1OOO) VAI PARA AUDITORIA 

	* - CORRECAO = 4
		- SE TODAS AS COMPETENCIAS ESTAO PREENCHIDAS
		- SE EXISTE PRIMEIRA, SEGUNDA E TERCEIRA 
		- SE FOR SOBERANA: DEVE SER ATUALIZADA A REDACAO (STATUS E DATA) 

	* - CORRECAO = 5 E 6 
		- SE TODAS AS COMPETENCIAS ESTAO PREENCHIDAS
		- NAO PODE EXISTIR OUTRA CORRECAO PARA ESTA REDACAO (PRIMEIRA, SEGUNDA, TERCEIRA, QUARTA, AUDITORA)
		- 

	* - AUDITORIA 
		- SE EXISTE DDH OU SE EXISTE DUAS NOTAS 1OOO 
		- SE NAO EXISTE OUTRA CORRECAO AUDITORIA PARA A MESMA REDACAO
		- 


*/	