
INSERT INTO TEMP_ALUNOS_NAO_IMPORTADOS
SELECT DISTINCT MOTIVO = 'PROBLEMA TURMA        ',* 
FROM TEMP_ALUNOS_NOVO 
WHERE TURMANOME LIKE '%,%'



SELECT *
--UPDATE TEM SET TEM.USUARIOSERIE = 'Extensivo'
FROM TEMP_ALUNOS_NOVO TEM WHERE USUARIOSERIE = '3ª série / Extensivo ,Extensivo '




SELECT ALU.* 
INTO TEMP_IMPORTAR_SAE
FROM TEMP_ALUNOS ALU LEFT JOIN AUTH_USER USU ON (ALU.USUARIOID = USU.USERNAME)
WHERE USU.ID IS NULL AND ALU.USUARIOID NOT IN (SELECT USUARIOID FROM TEMP_ALUNOS_NAO_IMPORTADOS)