--- SELECT ENTREGA ----- 

SELECT USU.ID AS ALUNO_ID, USU.NAME AS ALUNO_NOME, USU.PUBLIC_IDENTIFIER AS ALUNO_IDENTIFICADOR,
       COL.ID AS PROVA_ID, COL.NAME AS PROVA_NOME, EXA.ID AS EXAME_ID, EXA.NAME AS EXAME_NOME, 
	   VET.GABARITO_ALUNO, VET.GABARITO_EXAME
  FROM TMP_VETOR_RESPOSTA VET WITH(NOLOCK) JOIN AUTH_USER       USU WITH(NOLOCK) ON (USU.ID = VET.USER_ID)
                                           JOIN EXAM_EXAM       EXA WITH(NOLOCK) ON (EXA.ID = VET.exam_id) 
										   JOIN EXAM_COLLECTION COL WITH(NOLOCK) ON (COL.ID = VET.COLLECTION_ID)

